import type { AirulesConfig, AirulesConfigPack } from '@baicie/airules-schema'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { getAirulesAgentDir, resolveAirulesConfigPath } from './config-loader'

export function upsertConfigPack(
  config: AirulesConfig,
  packEntry: AirulesConfigPack,
): AirulesConfig {
  const index = config.packs.findIndex(pack => {
    if (packEntry.name && pack.name === packEntry.name) {
      return true
    }

    return pack.source === packEntry.source
  })

  const nextPacks: AirulesConfigPack[] = []
  for (const pack of config.packs) {
    nextPacks.push(pack)
  }

  if (index === -1) {
    nextPacks.push(packEntry)
  } else {
    const previous = nextPacks[index]
    const mergedVariables = mergeVariables(previous, packEntry)

    nextPacks[index] = {
      source: packEntry.source,
    }
    const updated = nextPacks[index]

    if (packEntry.name !== undefined) {
      updated.name = packEntry.name
    } else if (previous && previous.name !== undefined) {
      updated.name = previous.name
    }

    if (packEntry.profile !== undefined) {
      updated.profile = packEntry.profile
    } else if (previous && previous.profile !== undefined) {
      updated.profile = previous.profile
    }

    if (packEntry.agents !== undefined) {
      updated.agents = packEntry.agents
    } else if (previous && previous.agents !== undefined) {
      updated.agents = previous.agents
    }

    if (mergedVariables !== undefined) {
      updated.variables = mergedVariables
    }
  }

  return {
    version: 1,
    packs: nextPacks,
  }
}

function mergeVariables(
  previous: AirulesConfigPack | undefined,
  packEntry: AirulesConfigPack,
): Record<string, unknown> | undefined {
  const previousVariables =
    previous && previous.variables ? previous.variables : {}
  const nextVariables = packEntry.variables ? packEntry.variables : {}

  if (
    Object.keys(previousVariables).length === 0 &&
    Object.keys(nextVariables).length === 0
  ) {
    return undefined
  }

  const merged: Record<string, unknown> = {}
  for (const key of Object.keys(previousVariables)) {
    merged[key] = previousVariables[key]
  }
  for (const key of Object.keys(nextVariables)) {
    merged[key] = nextVariables[key]
  }

  return merged
}

export function writeAirulesConfig(cwd: string, config: AirulesConfig): void {
  const resolved = resolveAirulesConfigPath(cwd)
  const configPath =
    resolved !== null
      ? resolved.path
      : join(getAirulesAgentDir(cwd), 'airules.config.ts')

  mkdirSync(dirname(configPath), {
    recursive: true,
  })

  if (configPath.endsWith('.json')) {
    writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`)
    return
  }

  writeFileSync(configPath, renderTypeScriptConfig(config))
}

function renderTypeScriptConfig(config: AirulesConfig): string {
  return `// airules config (v1)
//
// Generated by airules. The default export is validated against
// the airules config schema. You can optionally import the typed helper
// from "@baicie/airules-schema" once it is installed in your project.

export default ${JSON.stringify(config, null, 2)}
`
}
