import type {
  AgentName,
  AirulesConfig,
  AirulesConfigPack,
} from '@baicie/airules-schema'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { getAirulesAgentDir, resolveAirulesConfigPath } from './config-loader'

export function upsertConfigPack(
  config: AirulesConfig,
  packEntry: AirulesConfigPack,
): AirulesConfig {
  const index = config.packs.findIndex(pack => {
    if (packEntry.name && pack.name === packEntry.name) {
      return true
    }

    return pack.source === packEntry.source
  })

  const nextPacks: AirulesConfigPack[] = []
  for (const pack of config.packs) {
    nextPacks.push(pack)
  }

  if (index === -1) {
    nextPacks.push(packEntry)
  } else {
    const previous = nextPacks[index]
    nextPacks[index] = mergeConfigPack(previous, packEntry)
  }

  return {
    version: 1,
    $schema: config.$schema,
    registries: config.registries,
    install: config.install,
    security: config.security,
    packs: nextPacks,
  }
}

function mergeConfigPack(
  previous: AirulesConfigPack | undefined,
  incoming: AirulesConfigPack,
): AirulesConfigPack {
  const next: AirulesConfigPack = {
    source: incoming.source,
  }

  if (incoming.name !== undefined) {
    next.name = incoming.name
  } else if (previous && previous.name !== undefined) {
    next.name = previous.name
  }

  if (incoming.profile !== undefined) {
    next.profile = incoming.profile
  } else if (previous && previous.profile !== undefined) {
    next.profile = previous.profile
  }

  const agents = mergeAgents(previous && previous.agents, incoming.agents)
  if (agents !== undefined) {
    next.agents = agents
  }

  const variables = mergeVariables(
    previous && previous.variables,
    incoming.variables,
  )
  if (variables !== undefined) {
    next.variables = variables
  }

  return next
}

function mergeAgents(
  previous: AgentName[] | undefined,
  incoming: AgentName[] | undefined,
): AgentName[] | undefined {
  if (!previous && !incoming) {
    return undefined
  }

  const result = new Set<AgentName>()
  for (const agent of previous !== undefined ? previous : []) {
    result.add(agent)
  }
  for (const agent of incoming !== undefined ? incoming : []) {
    result.add(agent)
  }

  return Array.from(result)
}

function mergeVariables(
  previous: Record<string, unknown> | undefined,
  incoming: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
  if (!previous && !incoming) {
    return undefined
  }

  const merged: Record<string, unknown> = {}
  for (const key of Object.keys(previous !== undefined ? previous : {})) {
    merged[key] = (previous !== undefined ? previous : {})[key]
  }
  for (const key of Object.keys(incoming !== undefined ? incoming : {})) {
    merged[key] = (incoming !== undefined ? incoming : {})[key]
  }

  return merged
}

export function writeAirulesConfig(cwd: string, config: AirulesConfig): void {
  const resolved = resolveAirulesConfigPath(cwd)
  const configPath =
    resolved !== null
      ? resolved.path
      : join(getAirulesAgentDir(cwd), 'airules.config.ts')

  mkdirSync(dirname(configPath), {
    recursive: true,
  })

  if (configPath.endsWith('.json')) {
    writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`)
    return
  }

  writeFileSync(configPath, renderTypeScriptConfig(config))
}

function renderTypeScriptConfig(config: AirulesConfig): string {
  return `// airules config (v1)
//
// Generated by airules. The default export is validated against
// the airules config schema. You can optionally import the typed helper
// from "@baicie/airules-schema" once it is installed in your project.

export default ${JSON.stringify(config, null, 2)}
`
}
