// airules config (v1)
//
// Generated by airules. The default export is validated against
// the airules config schema. You can optionally import the typed helper
// from "@baicie/airules-schema" once it is installed in your project.

export default {
  version: 1,
  install: {
    conflict: 'warn',
  },
  security: {
    trustedSources: [],
    allowScripts: false,
    requirePinnedVersion: false,
  },
  packs: [
    {
      source: './packs/react-shadcn',
      name: '@baicie/react-shadcn',
      agents: ['codex', 'cursor', 'skill'],
    },
  ],
}
